/**
 * Call OpenAI's GPT-4 Vision model to describe an image
 * @param imageBuffer - The image as a Buffer
 * @param apiKey - OpenAI API key
 * @returns Object with description and model name
 */
async function callOpenAIVision(
  imageBuffer: Buffer,
  apiKey: string
): Promise<{ description: string; modelName: string }> {
  const base64Image = imageBuffer.toString('base64');
  const mimeType = detectMimeType(imageBuffer);
  
  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: 'gpt-4o-mini',
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: 'Please describe this image in detail.'
            },
            {
              type: 'image_url',
              image_url: {
                url: `data:${mimeType};base64,${base64Image}`
              }
            }
          ]
        }
      ],
      max_tokens: 500
    })
  });

  if (!response.ok) {
    throw new Error(`OpenAI API error: ${response.status} ${response.statusText}`);
  }

  const data = await response.json();
  const description = data.choices[0]?.message?.content || 'No description generated';
  
  return {
    description,
    modelName: 'gpt-4o'
  };
}

/**
 * Call Grok's vision model to describe an image
 * @param imageBuffer - The image as a Buffer
 * @param apiKey - Grok API key (xAI)
 * @returns Object with description and model name
 */
async function callGrokVision(
  imageBuffer: Buffer,
  apiKey: string
): Promise<{ description: string; modelName: string }> {
  const base64Image = imageBuffer.toString('base64');
  const mimeType = detectMimeType(imageBuffer);
  
  const response = await fetch('https://api.x.ai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: 'grok-2-vision-1212',
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: 'Please describe this image in detail.'
            },
            {
              type: 'image_url',
              image_url: {
                url: `data:${mimeType};base64,${base64Image}`
              }
            }
          ]
        }
      ],
      max_tokens: 500
    })
  });

  if (!response.ok) {
    throw new Error(`Grok API error: ${response.status} ${response.statusText}`);
  }

  const data = await response.json();
  const description = data.choices[0]?.message?.content || 'No description generated';
  
  return {
    description,
    modelName: 'grok-2-vision-1212'
  };
}

/**
 * Detect MIME type from image buffer
 * @param buffer - Image buffer
 * @returns MIME type string
 */
function detectMimeType(buffer: Buffer): string {
  const signatures: { [key: string]: string } = {
    '89504e47': 'image/png',
    'ffd8ffe0': 'image/jpeg',
    'ffd8ffe1': 'image/jpeg',
    'ffd8ffe2': 'image/jpeg',
    '47494638': 'image/gif',
    '52494646': 'image/webp'
  };

  const hex = buffer.toString('hex', 0, 4);
  return signatures[hex] || 'image/jpeg';
}

/**
 * Function that can route to different AI models
 * @param imageBuffer - The image as a Buffer
 * @param model - Model name: 'openai', 'grok', or undefined for mock
 * @param apiKey - API key for the chosen provider
 */
async function callAIModel(
  imageBuffer: Buffer,
  model?: string,
  apiKey?: string
): Promise<{ description: string; modelName: string }> {
  
  if (!model || model === 'mock') {
    const modelName = 'mock-vision-1';
    const description = `This is a mocked description generated by ${modelName}. (size=${imageBuffer.length} bytes)`;
    return { description, modelName };
  }

  if (!apiKey) {
    throw new Error(`API key required for model: ${model}`);
  }

  switch (model.toLowerCase()) {
    case 'openai':
    case 'gpt-4o':
      return callOpenAIVision(imageBuffer, apiKey);
    
    case 'grok':
    case 'grok-2-vision':
      return callGrokVision(imageBuffer, apiKey);
    
    default:
      throw new Error(`Unsupported model: ${model}`);
  }
}

// Export functions
export { callAIModel, callOpenAIVision, callGrokVision, detectMimeType };